run_type: "gmme"
run: "gmme005i"

dataset:
  - "SVA1_COADD_BULLET"
#dataset:
#  - "SVA1_COADD_SPTE"
#  - "SVA1_COADD_ELGORDO"
#  - "SVA1_COADD_RXJ"
#  - "SVA1_COADD_BULLET"

withbands: ["g","r","i","z"]
band: [ "i" ]
medsconf: "011"
nper: 30

# this is the gmix_meds config file
# flat priors
config: "nmeds006"

head: ""
